
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int dospunts = 24;
  public static final int fer = 15;
  public static final int vector = 21;
  public static final int mentre = 14;
  public static final int programa = 4;
  public static final int cim = 32;
  public static final int amb = 19;
  public static final int openparent = 25;
  public static final int coma = 27;
  public static final int letra = 39;
  public static final int llegir = 17;
  public static final int fmentre = 16;
  public static final int blanc = 28;
  public static final int si = 10;
  public static final int escriure = 9;
  public static final int buida = 33;
  public static final int desempilar = 31;
  public static final int numero = 42;
  public static final int closeparent = 26;
  public static final int EOF = 0;
  public static final int binario = 41;
  public static final int ramificar = 18;
  public static final int error = 1;
  public static final int esquerra = 8;
  public static final int fsi = 11;
  public static final int si_no = 12;
  public static final int empilar = 29;
  public static final int fi = 6;
  public static final int llavors = 13;
  public static final int simbol = 22;
  public static final int framificar = 20;
  public static final int id = 40;
  public static final int cerrarllave = 36;
  public static final int tipus_pila = 23;
  public static final int relacional = 38;
  public static final int o = 3;
  public static final int dreta = 7;
  public static final int accepta = 5;
  public static final int en = 37;
  public static final int i = 2;
  public static final int abrirllave = 35;
  public static final int no = 34;
  public static final int empilar_par = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "i",
  "o",
  "programa",
  "accepta",
  "fi",
  "dreta",
  "esquerra",
  "escriure",
  "si",
  "fsi",
  "si_no",
  "llavors",
  "mentre",
  "fer",
  "fmentre",
  "llegir",
  "ramificar",
  "amb",
  "framificar",
  "vector",
  "simbol",
  "tipus_pila",
  "dospunts",
  "openparent",
  "closeparent",
  "coma",
  "blanc",
  "empilar",
  "empilar_par",
  "desempilar",
  "cim",
  "buida",
  "no",
  "abrirllave",
  "cerrarllave",
  "en",
  "relacional",
  "letra",
  "id",
  "binario",
  "numero"
  };
}

